@startmindmap

title 实现计划

* <&flag>Chat
** ❇️用户模块
*** ❇️登录注册（验证码，JWT）
*** ❇️用户详情
*** ❇️好友增删改查
** ❇️通讯模块
*** ❇️单人聊天室
*** ❇️多人聊天室
*** ❇️语音视频
*** ❇️发送信息支持多媒体（语音，视频，图片）
** ❇️朋友圈模块
*** ❇️朋友圈增删改查
*** ❇️朋友圈信息支持多媒体（语音，视频，图片）
*** ❇️朋友圈点赞，评论

center footer https://github.com/pkc918

@endmindmap