server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  dbname: chat
  username: root
  password: 123456
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai
email:
  host: smtp.qq.com
  port: 465
  from: 2489964425@qq.com
  subject: WeChat-Plus 验证码
  password: 你的qq邮箱授权码
  serverName: smtp.qq.com